name: fittnes_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/bkg.jpg
    - assets/images/f.jpg
    - assets/images/f2.jpg
    - assets/images/m1.jpg
    - assets/images/m3.jpg
    - assets/images/don.jpg
    - assets/images/rope.jpg
    - assets/images/pull.jpg
    - assets/images/yoga.jpg
    - assets/images/pullm.jpg
    - assets/images/bkg1.jpg
    - assets/images/b1f.jpg
    - assets/images/yy.jpg
    - assets/images/yyy.jpg



